### ISSUE TITLE
wAR token integration

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/cyberpunk-beavers#45]

**Comment by stasiakmatt** [comment]
wAR process
https://www.ao.link/token#/token/xU9zFkq3X2ZQ6olwNVvr1vUWIjc3kXTWr7xKQD6dh10

Our ArConnect wallet for integration: jnioZFibZSCcV8o-HkBXYPYEYNib4tqfexP0kCBXX_M

**Comment by stasiakmatt** [comment]
USDC -> wAR swap

1. First choice, https://wardepot.g8way.io
2. Potential alts, need to double check before any actions, testnet: arswap.org, permaswap.network
